<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\OnionCompany.Application\OnionCompany.Application.csproj" />
    <ProjectReference Include="..\..\Core\OnionCompany.Contract\OnionCompany.Contract.csproj" />
  </ItemGroup>

</Project>
